pub mod text_rendering {
    pub fn get_character_coords(
        character: &char,
        character_width: i32,
        character_height: i32,
    ) -> Vec<(i32, i32)> {
        match character {
            'a' => vec![
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
                (0, character_height - character_height / 4),
                (character_width, character_height - character_height / 4),
            ],
            'b' => vec![
                (0, 0),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
                (0, character_height / 2),
            ],
            'c' => vec![
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
            ],
            'd' => vec![
                (character_width, 0),
                (character_width, character_height),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
            ],
            'e' => vec![
                (character_width, character_height),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height - character_height / 4),
                (0, character_height - character_height / 4),
            ],
            'f' => vec![
                (character_width / 2, character_height * 5 / 4),
                (character_width / 2, character_height / 4),
                (0, character_height / 4),
                (character_width, character_height / 4),
                (character_width / 2, character_height / 4),
                (character_width / 2, 0),
                (character_width, 0),
            ],
            'g' => vec![
                (character_width, character_height),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height * 5 / 4),
                (0, character_height * 5 / 4),
            ],
            'h' => vec![
                (0, 0),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
            ],
            'i' => vec![
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
                (character_width / 2, character_height),
                (character_width / 2, character_height / 2),
                (character_width / 4, character_height / 2),
            ],
            'j' => vec![
                (character_width / 4, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 5 / 4),
                (0, character_height * 5 / 4),
            ],
            'k' => vec![
                (character_width, character_height),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (0, character_height / 3),
                (character_width, character_height / 3),
                (0, character_height / 3),
                (0, 0),
            ],
            'l' => vec![
                (character_width / 4, 0),
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
            ],
            'm' => vec![
                (0, character_height),
                (0, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
            ],
            'n' => vec![
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
            ],
            'o' => vec![
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
                (0, character_height / 2),
            ],
            'p' => vec![
                (0, character_height * 5 / 4),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
            ],
            'q' => vec![
                (character_width, character_height * 5 / 4),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
            ],
            'r' => vec![
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
            ],
            's' => vec![
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height - character_height / 4),
                (character_width, character_height - character_height / 4),
                (character_width, character_height),
                (0, character_height),
            ],
            't' => vec![
                (character_width, character_height),
                (character_width / 2, character_height),
                (character_width / 2, character_height / 4),
                (0, character_height / 4),
                (character_width, character_height / 4),
                (character_width / 2, character_height / 4),
                (character_width / 2, 0),
            ],
            'u' => vec![
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
            ],
            'v' => vec![
                (0, character_height / 2),
                (character_width / 2, character_height),
                (character_width, character_height / 2),
            ],
            'w' => vec![
                (0, character_height / 2),
                (0, character_height),
                (character_width / 2, character_height),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
            ],
            'x' => vec![
                (0, character_height / 2),
                (character_width, character_height),
                (character_width / 2, character_height - character_height / 4),
                (0, character_height),
                (character_width, character_height / 2),
            ],
            'y' => vec![
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height * 5 / 4),
                (0, character_height * 5 / 4),
                (character_width, character_height * 5 / 4),
                (character_width, character_height / 2),
            ],
            'z' => vec![
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height - character_height / 4),
                (0, character_height - character_height / 4),
                (0, character_height),
                (character_width, character_height),
            ],
            '0' => vec![
                (0, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (character_width / 2, 0),
                (character_width, 0),
                (character_width, character_height),
                (0, character_height),
                (0, 0),
            ],
            '1' => vec![
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
                (character_width / 2, character_height),
                (character_width / 2, 0),
                (character_width / 4, 0),
            ],
            '2' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
            ],
            '3' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
            ],
            '4' => vec![
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (character_width, 0),
            ],
            '5' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
            ],
            '6' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
                (0, character_height / 2),
            ],
            '7' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
            ],
            '8' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, 0),
            ],
            '9' => vec![
                (0, character_height),
                (character_width, character_height),
                (character_width, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
            ],
            ',' => vec![
                (character_width / 2, character_height),
                (character_width / 2, character_height * 5 / 4),
            ],
            '.' => vec![
                (character_width / 2, character_height),
                (character_width / 2, character_height * 11 / 12),
            ],
            '\'' => vec![
                (character_width / 2, 0),
                (character_width / 2, -character_height / 3),
            ],
            '"' => vec![
                (character_width * 1 / 3, 0),
                (character_width * 1 / 3, -character_height / 3),
                (character_width * 2 / 3, 0),
                (character_width * 2 / 3, -character_height / 3),
            ],
            '`' => vec![
                (character_width * 3 / 5, 0),
                (character_width * 2 / 5, -character_height / 3),
            ],
            '+' => vec![
                (character_width / 4, character_height / 2),
                (character_width * 3 / 4, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 2, character_height / 4),
            ],
            '-' => vec![
                (character_width / 4, character_height / 2),
                (character_width * 3 / 4, character_height / 2),
            ],
            '*' => vec![
                (character_width / 6, character_height * 3 / 7),
                (character_width / 2, character_height / 2),
                (character_width * 5 / 6, character_height * 3 / 7),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width * 5 / 6, character_height * 5 / 7),
                (character_width / 2, character_height / 2),
                (character_width / 6, character_height * 5 / 7),
            ],
            '/' => vec![(0, character_height), (character_width, 0)],
            '=' => vec![
                (character_width / 4, character_height * 2 / 5),
                (character_width * 3 / 4, character_height * 2 / 5),
                (character_width / 4, character_height * 3 / 5),
                (character_width * 3 / 4, character_height * 3 / 5),
            ],
            '\\' => vec![(0, 0), (character_width, character_height)],
            '#' => vec![
                (character_width / 4, 0),
                (character_width / 4, character_height),
                (character_width / 4, character_height / 4),
                (0, character_height / 4),
                (character_width, character_height / 4),
                (character_width * 3 / 4, character_height / 4),
                (character_width * 3 / 4, 0),
                (character_width * 3 / 4, character_height),
                (character_width * 3 / 4, character_height / 4),
                (character_width * 3 / 4, character_height * 3 / 4),
                (character_width, character_height * 3 / 4),
                (0, character_height * 3 / 4),
            ],
            '(' => vec![
                (character_width * 3 / 4, 0),
                (character_width / 4, character_height / 4),
                (character_width / 4, character_height * 3 / 4),
                (character_width * 3 / 4, character_height),
            ],
            ')' => vec![
                (character_width / 4, 0),
                (character_width * 3 / 4, character_height / 4),
                (character_width * 3 / 4, character_height * 3 / 4),
                (character_width / 4, character_height),
            ],
            '[' => vec![
                (character_width * 3 / 4, 0),
                (character_width / 4, 0),
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
            ],
            ']' => vec![
                (character_width / 4, 0),
                (character_width * 3 / 4, 0),
                (character_width * 3 / 4, character_height),
                (character_width / 4, character_height),
            ],
            '{' => vec![
                (character_width, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height * 5 / 11),
                (character_width / 4, character_height / 2),
                (character_width / 2, character_height * 6 / 11),
                (character_width / 2, character_height),
                (character_width, character_height),
            ],
            '}' => vec![
                (0, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height * 5 / 11),
                (character_width * 3 / 4, character_height / 2),
                (character_width / 2, character_height * 6 / 11),
                (character_width / 2, character_height),
                (0, character_height),
            ],
            '^' => vec![
                (0, character_height / 4),
                (character_width / 2, 0),
                (character_width, character_height / 4),
            ],
            '°' => vec![
                (character_width / 4, 0),
                (character_width * 3 / 4, 0),
                (character_width * 3 / 4, character_height / 4),
                (character_width / 4, character_height / 4),
                (character_width / 4, 0),
            ],
            '$' => vec![
                (character_width, 0),
                (character_width / 2, 0),
                (character_width / 2, -character_height / 4),
                (character_width / 2, character_height * 5 / 4),
                (character_width / 2, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 2, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
            ],
            '%' => vec![
                (character_width, 0),
                (character_width / 2, character_height / 2),
                (0, character_height / 2),
                (0, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height * 3 / 4),
                (character_width / 2, character_height / 2),
                (0, character_height),
            ],
            '<' => vec![
                (character_width, character_height / 4),
                (0, character_height / 2),
                (character_width, character_height * 3 / 4),
            ],
            '>' => vec![
                (0, character_height / 4),
                (character_width, character_height / 2),
                (0, character_height * 3 / 4),
            ],
            '?' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
                (character_width / 2, character_height * 3 / 4),
            ],
            '!' => vec![
                (character_width / 2, 0),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 4, character_height),
                (character_width * 3 / 4, character_height),
                (character_width / 2, character_height * 3 / 4),
            ],
            ':' => vec![
                (character_width / 2, character_height / 2),
                (character_width / 4, character_height / 4),
                (character_width * 3 / 4, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width / 4, character_height * 3 / 4),
                (character_width * 3 / 4, character_height * 3 / 4),
                (character_width / 2, character_height / 2),
            ],
            ';' => vec![
                (character_width / 2, character_height / 2),
                (character_width / 4, character_height / 4),
                (character_width * 3 / 4, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height),
            ],
            '&' => vec![
                (character_width, character_height),
                (0, character_height / 3),
                (character_width / 2, 0),
                (character_width * 3 / 4, character_height / 4),
                (0, character_height * 2 / 3),
                (character_width / 2, character_height),
                (character_width, character_height * 2 / 3),
            ],
            '|' => vec![
                (character_width / 2, 0),
                (character_width / 2, character_height),
            ],
            '_' => vec![(0, character_height), (character_width, character_height)],
            '~' => vec![
                (0, character_height * 3 / 5),
                (character_width / 3, character_height * 2 / 5),
                (character_width * 3 / 5, character_height * 3 / 5),
                (character_width, character_height * 2 / 5),
            ],
            '€' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height / 3),
                (character_width / 2, character_height / 3),
                (0, character_height / 3),
                (0, character_height * 2 / 3),
                (character_width / 2, character_height * 2 / 3),
                (0, character_height * 2 / 3),
                (0, character_height),
                (character_width, character_height),
            ],
            'A' => vec![
                (0, character_height),
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
            ],
            'B' => vec![
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (character_width / 3, character_height / 2),
            ],
            'C' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height),
                (character_width, character_height),
            ],
            'D' => vec![
                (0, 0),
                (character_width * 4 / 5, 0),
                (character_width * 4 / 5, character_height / 6),
                (character_width, character_height / 6),
                (character_width, character_height * 5 / 6),
                (character_width * 4 / 5, character_height * 5 / 6),
                (character_width * 4 / 5, character_height),
                (0, character_height),
                (0, 0),
            ],
            'E' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
            ],
            'F' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
            ],
            'G' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height),
                (character_width, character_height),
                (character_width, character_height / 2),
                (character_width / 2, character_height / 2),
            ],
            'H' => vec![
                (0, 0),
                (0, character_height),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, 0),
                (character_width, character_height),
            ],
            'I' => vec![
                (0, 0),
                (character_width, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (0, character_height),
                (character_width, character_height),
            ],
            'J' => vec![
                (0, 0),
                (character_width, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (0, character_height),
            ],
            'K' => vec![
                (character_width, character_height),
                (character_width, character_height * 5 / 12),
                (0, character_height * 5 / 12),
                (0, character_height),
                (0, 0),
                (0, character_height * 7 / 12),
                (character_width, character_height * 7 / 12),
                (character_width, 0),
            ],
            'L' => vec![
                (0, 0),
                (0, character_height),
                (character_width, character_height),
            ],
            'M' => vec![
                (0, character_height),
                (0, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (character_width / 2, 0),
                (character_width, 0),
                (character_width, character_height),
            ],
            'N' => vec![
                (0, character_height),
                (0, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (character_width, character_height),
                (character_width, 0),
            ],
            'O' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height),
                (0, character_height),
                (0, 0),
            ],
            'P' => vec![
                (0, character_height),
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (0, character_height / 2),
            ],
            'Q' => vec![
                (character_width, character_height),
                (0, character_height),
                (0, 0),
                (character_width, 0),
                (character_width, character_height),
                (character_width / 2, character_height),
                (character_width / 2, character_height / 2),
            ],
            'R' => vec![
                (0, character_height),
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (character_width * 3 / 4, character_height / 2),
                (character_width * 3 / 4, character_height),
            ],
            'S' => vec![
                (character_width, 0),
                (0, 0),
                (0, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 2, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (character_width, character_height),
                (0, character_height),
            ],
            'T' => vec![
                (0, 0),
                (character_width, 0),
                (character_width / 2, 0),
                (character_width / 2, character_height),
            ],
            'U' => vec![
                (0, 0),
                (0, character_height),
                (character_width, character_height),
                (character_width, 0),
            ],
            'V' => vec![
                (0, 0),
                (character_width / 2, character_height),
                (character_width, 0),
            ],
            'W' => vec![
                (0, 0),
                (0, character_height),
                (character_width / 2, character_height),
                (character_width / 2, 0),
                (character_width / 2, character_height),
                (character_width, character_height),
                (character_width, 0),
            ],
            'X' => vec![
                (0, 0),
                (character_width, character_height),
                (character_width / 2, character_height - character_height / 2),
                (0, character_height),
                (character_width, 0),
            ],
            'Y' => vec![
                (character_width / 2, character_height),
                (character_width / 2, character_height / 2),
                (0, character_height / 2),
                (0, 0),
                (0, character_height / 2),
                (character_width, character_height / 2),
                (character_width, 0),
            ],
            'Z' => vec![
                (0, 0),
                (character_width, 0),
                (character_width, character_height / 2),
                (character_width / 2, character_height / 2),
                (character_width / 2, character_height * 3 / 4),
                (character_width / 2, character_height / 4),
                (character_width / 2, character_height / 2),
                (character_width, character_height / 2),
                (0, character_height / 2),
                (0, character_height),
                (character_width, character_height),
            ],
            _ => vec![],
        }
    }
}
